name: test, deploy and run
on:
# run with every push
  push:
# run if manually triggered
  workflow_dispatch:
# deploy on a recurring schedule to avoid OOM problems
#  schedule:
#    - cron: '15 */6 * * *'

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1.0.0
      - run: cd client; make build
      - uses: actions/upload-artifact@master
        with:
          name: client.tgz
          path: client.tgz
  deploy-frontend:
    runs-on: ubuntu-latest
    environment: live
    steps:
      - uses: actions/download-artifact@master
        with:
          name: client.tgz
          path: client.tgz
      - name: Deploy to live server via ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
  #          systemctl --user restart superstonkModerationBot.service
            echo "That's all folks"
