name: test, deploy and run
on:
# run with every push
  push:
# run if manually triggered
  workflow_dispatch:
# deploy on a recurring schedule to avoid OOM problems
#  schedule:
#    - cron: '15 */6 * * *'

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1.0.0
      - name: create artifact
        run: cd client; make build
      - name: store artifact
        uses: actions/upload-artifact@master
        with:
          name: client.tgz
          path: client/client.tgz
  deploy-frontend:
    runs-on: ubuntu-latest
    needs: build-frontend
    environment: live
    steps:
      - name: download artifact
        uses: actions/download-artifact@master
        with:
          name: client.tgz
          path: client.tgz
#      - name: scp to target
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.HOST }}
#          username: ${{ secrets.USERNAME }}
#          key: ${{ secrets.SSH_KEY }}
#          script: |
#  #          systemctl --user restart superstonkModerationBot.service
#            echo "That's all folks"
