name: test, deploy and run
on:
# run with every push
  push:
# run if manually triggered
  workflow_dispatch:
# deploy on a recurring schedule to avoid OOM problems
#  schedule:
#    - cron: '15 */6 * * *'

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1.0.0
      - name: create artifact
        run: cd client; make production
      - name: store artifact
        uses: actions/upload-artifact@master
        with:
          name: client
          path: client/dist/spa
  deploy-frontend:
    runs-on: ubuntu-latest
    needs: build-frontend
    environment: live
    steps:
      - name: download artifact
        uses: actions/download-artifact@master
        with:
          name: client
          path: client
      - name: debug
        run: ls ; ls -la
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: client
          target: "modwebsite-live/"
          rm: true
